# World tick - runs every minute in dev for faster testing
development:
  world_tick:
    class: WorldTickJob
    queue: default
    schedule: every minute

production:
  world_tick:
    class: WorldTickJob
    queue: default
    schedule: every 2 minutes

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
